<template>
    <div>

        <div class="projects-display-container">

            <div
                v-for="(project, projectIndex) in projects"
                :key="projectIndex"
                class="project-container"
            >
                <div class="project-display-container">
                
                    <div class="project-photo-container">
                        
                        <!-- loading overlay - gives time for iframes to load -->
                        <div v-show="isLoading" class="loading-frame">
                            
                            <div>
                                <svg 
                                    xmlns="http://www.w3.org/2000/svg" 
                                    xmlns:xlink="http://www.w3.org/1999/xlink" 
                                    style="margin: auto; background: transparent; display: block; shape-rendering: auto; animation-play-state: running; animation-delay: 0s;" 
                                    class="loading-gif" 
                                    viewBox="0 0 100 100" 
                                    preserveAspectRatio="xMidYMid"
                                >
                                    <path 
                                        fill="none" 
                                        stroke="#ffa7ff" 
                                        stroke-width="8" 
                                        stroke-dasharray="42.76482137044271 42.76482137044271" 
                                        d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" 
                                        stroke-linecap="round" 
                                        style="transform: scale(0.8); transform-origin: 50px 50px; animation-play-state: running; animation-delay: 0s;"
                                    >
                                        <animate 
                                            attributeName="stroke-dashoffset"  
                                            repeatCount="indefinite" 
                                            dur="1s" 
                                            keyTimes="0;1" 
                                            values="0;256.58892822265625" 
                                            style="animation-play-state: running; animation-delay: 0s;"
                                        />
                                    </path>
                                <!-- [ldio] generated by https://loading.io/ -->
                                </svg>
                            </div>

                            <div>
                                Content Loading
                            </div>
                        </div>
                        
                        <iframe
                            v-if="project.visualRepersentation.iframe"
                            :src="project.visualRepersentation.pathToVisual"
                            class="iframe-size" 
                        />

                        <img 
                            v-else
                            :src="require(`@/assets/projectPhotos/${project.visualRepersentation.pathToVisual}`)"
                            class="project-photo" 
                            :alt="'photo of ' + project.description.title"
                        >

                    </div>

                    <div class="project-info-container">
                        
                        <div class="project-title-container">
                            {{ project.description.title }}
                        </div>

                        <div class="outbound-icons-container">
                            <div
                                v-for="(link, linkIndex) in project.externalLinks"
                                :key="linkIndex" 
                                class="outbound-link-container"
                                @click="openInNewTab(link.url)"
                            >
                                <fa-icon :icon="link.icon || 'globe'" :class="`outbound-icon ${link.iconColor || 'blue'}`" />
                                <span class="outbound-icon-text">
                                    {{ link.text || 'Default Text' }}
                                </span>
                            </div>
                        </div>
                        
                        <div class="project-short-description-container">
                            {{ project.description.shortText }}
                        </div>

                        <div class="tags-container">
                            <div
                                v-for="tag in project.tags"
                                :key="tag"
                                class="tag-container"
                            >
                                <fa-icon icon="hashtag" class="hashtag" />
                                {{ tag }}
                            </div>
                        </div>

                    </div>

                </div>

                <div>

                    <!-- toggle full tech stack with icons -->
                    <div
                        v-if="project.technologies" 
                        class="drop-down-toggle-container" 
                        @click="toggleStack(project.name)"
                    >
                        <span>
                            <span>
                                <fa-icon icon="eye" class="dropdown-icon"/>
                            </span>
                            {{ showingStack === project.name ? 'Hide' : 'Show' }} Project Stack
                        </span>
                    </div>

                    <collapse-transition :duration="500">
                        <div v-show="showingStack === project.name" class="all-technologies-container">
                            <div
                                v-for="(techInfo, stackSide) in project.technologies"
                                :key="stackSide"
                                class="technologies-container"
                            >
                                <div :class="`stack-side-header ${stackSide}`">
                                    {{ capitalize(stackSide) }}
                                </div>
                                <div class="technology-ordering">
                                    <div
                                        v-for="tech in project.technologies[stackSide]"
                                        :key="tech"
                                        class="technology-container"
                                    >
                                        <div>
                                            <fa-icon 
                                                :icon="techStackIcons(tech).icon" 
                                                :class="`technology-icon ${techStackIcons(tech).color}`" 
                                            />
                                        </div>
                                        <div class="technology-text">
                                            {{ capitalize(tech) }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </collapse-transition>

                    <!-- toggle long explanation -->
                    <div>
                        <div class="drop-down-toggle-container" @click="toggleProjectExplanation(project.name)">
                            <span>
                                <fa-icon icon="book" class="dropdown-icon"/>
                            </span>
                            {{ showingExplanation === project.name ? 'Hide' : "Show" }} Long Explanation
                        </div>
                    </div>

                    <collapse-transition :duration="500">
                        <div v-show="showingExplanation === project.name" class="long-project-explanation">
                            {{ project.description.longText }}
                        </div>
                    </collapse-transition>

                </div>
            </div>
        </div>
        
    </div>
</template>

<script>
import projects from './projects.json'

import urlHelpers from '@/libraries/urls.js'

import { CollapseTransition } from "@ivanv/vue-collapse-transition"

export default {
    name: "portfolio",
    components: {
        // eslint-disable-next-line
        CollapseTransition
    },
    data() {
        return {
            projects,
            showingStack: '',
            showingExplanation: '',
            // the amount of time to wait before showing iframes
            loadingTime: 3_500,
            isLoading: true
        }
    },
    methods: {
        openInNewTab(url="https://random.site") {
            return urlHelpers.openURLInNewTab(url)
        },
        capitalize(str="hi") {
            return str.slice(0, 1).toUpperCase() + str.slice(1)
        },
        toggleStack(projectName="khateebRemind") {
            return this.toggleDropdownItem("showingStack", projectName)
        },
        toggleProjectExplanation(projectName="khateebRemind") {
            return this.toggleDropdownItem("showingExplanation", projectName)
        },
        toggleDropdownItem(keyName="showingStack", projectName="khateebRemind") {
            if (this[keyName]=== projectName)
                return this['reset' + this.capitalize(keyName)]()
            else
                return this[keyName] = projectName
        },
        resetDropdownItem(keyName="showingStack") {
            return this[keyName] = 'none'
        },
        resetShowingStack() {
            return this.resetDropdownItem("showingStack")
        },
        resetShowingExplanation() {
            return this.resetDropdownItem("showingExplanation")
        },
        techStackIcons(techName="javascript") {
            switch(techName) {
                case "vue":
                    return { icon: ['fab', 'vuejs'], color: 'green' }
                case 'SASS':
                    return { icon: ['fab', 'sass'], color: 'pink' }
                case "javascript":
                    return { icon: ['fab', 'js'], color: 'orange' }
                case 'docker':
                    return { icon: ['fab', 'docker'], color: 'blue' }
                case "PWA":
                    return { icon: 'mobile-alt', color: 'purple' }
                case "python":
                    return { icon: ['fab', 'python'], color: 'yellow' }
                case 'mongo':
                case 'postgres':
                    return { icon: 'database', color: 'red' }
                case 'express':
                case 'flask':
                case 'feathers':
                    return { icon: 'server' }
                case 'bootstrap':
                    return { icon: ['fab', 'bootstrap'], color: 'purple' }
                case "AWS":
                    return { icon: ['fab', 'aws'], color: 'orange' }
                case 'node':
                    return { icon: ['fab', 'node-js'], color: 'green' }
                case 'tensorflow':
                    return { icon: 'brain', color: 'pink' }
                default:
                    return { icon: techName }
            }
        },
        removeLoadingOverlay() {
            return window.setTimeout(() => this.isLoading = false, this.loadingTime)
        }
    },
    computed: {
        project1() {
            return this.projects[0]
        }
    },
    created() {
        this.removeLoadingOverlay()
        this.resetShowingStack()
        this.resetShowingExplanation()
    }
}
</script>

<style lang="scss" scoped>
.projects-display-container {
    margin-bottom: 50px;
}

.project-display-container {
    position: relative;
    margin-top: 50px;
    width: 90%;
    max-width: 1400px;
    flex-direction: column;
    margin-left: auto;
    margin-right: auto;
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
}

.project-photo-container {
    width: 90vw;
    height: 60vw;
    position: relative;
    z-index: 1;
    margin-bottom: 20px;
    overflow: hidden;
    border: none;
    outline: none;
}

.project-photo {
    width: 100%;
    height: 100%;
}

.iframe-size {
    height: 100%;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    border: none;
    outline: none;
}

.project-info-container {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    position: relative;
    z-index: 2;
    text-align: left;
}

.project-title-container {
    font-size: 30px;
}

.project-short-description-container {
    font-size: 17px;
    color: getColor('silver');
    position: relative;
    top: 20px;
    background: getColor('dark-grey', 0.8);
    border-radius: 4px;
    padding-top: 20px;
    padding-bottom: 20px;
}

.dropdown-icon {
    color: getColor('purple');
    margin-right: 5px;
}

.drop-down-toggle-container {
    font-size: 15px;
    cursor: pointer;
    text-align: center;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;

    &:hover {
        color: getColor("light-blue");
    }
}

.tags-container {
    margin-top: 40px;
    display: flex;
    flex-wrap: wrap;
}

.tag-container {
    background: getColor("light-red");
    margin-right: 12px;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 4px;
    padding-right: 4px;
    border-radius: 4px;
    margin-bottom: 10px;

    &:hover {
        background: getColor("light-blue");
        cursor: default;
    }
}

.outbound-icons-container {
    margin-top: 20px;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
    align-items: center;
}

.outbound-link-container {
    margin-bottom: 7px;
}

.outbound-icon-text {
    margin-right: 20px;
    cursor: pointer;

    &:hover {
        color: getColor("light-purple");
    }
}

.technologies-container {
    margin-top: 20px;
    margin-left: 30px;
    margin-right: 30px;
}

.all-technologies-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
}

.outbound-icon {
    font-size: 13px;
    margin-right: 3px;
    color: getColor('light-blue');

    &.green {
        color: getColor('light-green');
    }

    &.orange {
        color: getColor("light-orange");
    }
}

// this has to be one of the worst names ever
// but I couldn't think of a better one :(
.technology-ordering {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    margin-top: 10px;
}

.long-project-explanation {
    margin-top: 10px;
    color: getColor("silver");
    width: 90%;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
}

.technology-container {
    margin-top: 5px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    margin-left: 20px;
    margin-right: 20px;
}

.project-container {
    margin-bottom: 150px;
}

.stack-side-header {
    color: getColor('light-purple');

    &.client {
        color: getColor('light-red');
    }

    &.server {
        color: getColor('light-blue');
    }

    &.devOps {
        color: getColor('light-orange');
    }
}

.technology-icon {
    margin-bottom: 2px;

    &.green {
        color: getColor('light-green');
    }

    &.purple {
        color: getColor('light-purple');
    }

    &.orange {
        color: getColor('light-orange');
    }

    &.red {
        color: getColor('light-red');
    }

    &.blue {
        color: getColor('light-blue');
    }

    &.pink {
        color: getColor('light-pink');
    }

    &.yellow {
        color: yellow;
    }
}

.outbound-icon {
    font-size: 13px;
    margin-right: 3px;
    color: getColor('light-blue');

    &.green {
        color: getColor('light-green');
    }

    &.orange {
        color: getColor("light-orange");
    }
}

.hashtag {
    font-size: 12px;
}

.loading-frame {
    width: 100%;
    height: 100%;
    position: relative;
    z-index: 2;
    font-size: 19px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.loading-gif {
    width: 50%;
}

.stack-icon {
    color: getColor("light-purple");
    margin-right: 5px;
}

@media screen and (min-width: $tabletWidth) {
    .drop-down-toggle-container {
        font-size: 18px;
        width: 240px;
    }
}

@media screen and (min-width: $desktopWidth) {
    .projects-display-container {
        margin-top: 90px;
        margin-bottom: 80px;
    }

    .project-display-container {
        flex-direction: row;
    }

    .project-info-container {
        width: 40%;
        margin-right: 0;
    }
    
    .tags-container {
        justify-content: flex-end;
    }

    .outbound-icon-text {
        margin-left: 0;
        margin-right: 1px;

        &:last-child {
            margin-right: 0;
        }
    }

    .outbound-icon {
        margin-left: 18px;
    }

    .tag-container {
        &:last-child {
            margin-right: 0px;
        }
    }
    
    .outbound-icons-container {
        justify-content: flex-end;
        width: 100%;
    }

    .project-title-container {
        font-size: 40px;
        text-align: right;
    }

    .project-short-description-container {
        font-size: 15px;
        color: getColor('silver');
        position: relative;
        width: 120%;
        right: 27.5%;
        background: getColor('grey', 1);
        min-height: 130px;
        padding-left: 20px;
        padding-right: 20px;
    }


    .project-photo-container {
        width: 50vw;
        max-width: 830px;
        height: 30vw;
        max-height: 500px;
        min-height: 400px;
        margin-bottom: 20px;
    }

    .drop-down-toggle-container {
        font-size: 20px;
        margin-top: 20px;
        width: 250px;
    }

    .technologies-container {
        margin-top: 40px;
    }
}
</style>