import { 
    faBars, 
    faLaptopCode, 
    faGlobe,
    faCodeBranch,
    faHashtag,
    faServer,
    faMobileAlt,
    faDatabase,
    faHammer,
    faArrowRight,
    faArrowDown,
    faMailBulk,
    faBrain,
    faPen,
    faNewspaper
} from '@fortawesome/free-solid-svg-icons'

import {
    faJs,
    faVuejs,
    faSass,
    faDocker,
    faNodeJs,
    faLinkedinIn,
    faGithub,
    faPython,
    faRust,
    faBootstrap,
    faGithubAlt,
    faLinkedin,
    faAws
} from '@fortawesome/free-brands-svg-icons'

export default [
    faLaptopCode,
    faBars,
    faGlobe,
    faCodeBranch,
    faHashtag,
    faServer,
    faJs,
    faVuejs,
    faSass,
    faMobileAlt,
    faDocker,
    faDatabase,
    faNodeJs,
    faHammer,
    faArrowRight,
    faArrowDown,
    faMailBulk,
    faLinkedinIn,
    faGithub,
    faPython,
    faRust,
    faBrain,
    faBootstrap,
    faPen,
    faGithubAlt,
    faLinkedin,
    faAws,
    faNewspaper
]